// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// dotenv is optional: on the server (e.g. Docker) DATABASE_URL is set in the environment.
import { createRequire } from "node:module";
import { defineConfig } from "prisma/config";

try {
  const req = createRequire(import.meta.url);
  req("dotenv/config");
} catch {
  // dotenv not installed or not ESM; rely on process.env (e.g. Docker)
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
